import RationaleReader
#check RationaleReader.original_comparison
#print axioms RationaleReader.original_comparison
#check RationaleReader.update_read_counterexample
#print axioms RationaleReader.update_read_counterexample
#check RationaleReader.cached_freshness_refuted
#print axioms RationaleReader.cached_freshness_refuted
#check RationaleReader.unchanged_update_retained
#print axioms RationaleReader.unchanged_update_retained
#check RationaleReader.budget_change_is_distinct
#print axioms RationaleReader.budget_change_is_distinct
#check RationaleReader.namedUniversalTruth
#print axioms RationaleReader.namedUniversalTruth
#check RationaleReader.encoded_statement
#print axioms RationaleReader.encoded_statement
#check RationaleReader.different_statement_refuted
#print axioms RationaleReader.different_statement_refuted
#check RationaleReader.proof_of_different_claim
#print axioms RationaleReader.proof_of_different_claim
#check RationaleReader.revised_method_retains_case
#print axioms RationaleReader.revised_method_retains_case
